version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=VishalSingh1
      - MYSQL_ROOT_PASSWORD=VishalSingh1
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: