version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: