version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=VishalSingh1
      - MYSQL_ROOT_PASSWORD=VishalSingh1
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://aws-database.caqc2qacqdrh.us-east-2.rds.amazonaws.com:3306/demo",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "VishalSingh1",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: