version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=VishalSingh1
      - MYSQL_ROOT_PASSWORD=VishalSingh1
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sqlinit.sql
      - db:/var/lib/mysql
volumes:
  db: