version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_USER=admin
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=VishalSingh1
      - MYSQL_ROOT_PASSWORD=VishalSingh1
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/demo?useSSL=false",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "VishalSingh1",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: