server:
  port: '9090'

logging:
  level:
    root: DEBUG
    com:
      schoool:
        management: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      student-management-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      retry-service:
        maxAttempts: 10
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
#        retryExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.io.IOException
#        ignoreExceptions:

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

kafka:
  producer:
    bootstrap-servers: 'http://127.0.0.1:9092'