server:
  port: '9090'

spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: 'jdbc:mysql://mysqldb:3306/demo?useSSL=false'
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com:
      springboot:
        tutorial: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false

application:
  access-level:
    student: ADMIN
    course: ADMIN
    schedule: ADMIN