server:
  port: '9090'

spring:
  profiles:
    active: local
  datasource:
    url: 'jdbc:mysql://mysqldb:3306/demo?allowPublicKeyRetrieval=true&useSSL=false'
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
#        hbm2ddl:
#          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: true

logging:
  level:
    root: DEBUG
    com:
      springboot:
        tutorial: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      test-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
      course-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      retry-service:
        maxAttempts: 10
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
#        retryExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.io.IOException
#        ignoreExceptions:

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

kafka:
  producer:
    bootstrap-servers: 'http://127.0.0.1:9092'
  consumer:
    bootstrap-servers: 'http://127.0.0.1:9092'
    group-id: 'school-service'

application:
  access-level:
    student: ADMIN
    course: ADMIN
    schedule: ADMIN